version: '3.8'

services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./.vscode:/app/.vscode
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8001
      - FLASK_APP=application.py
      - FLASK_CONFIG=DEV
    command: tail -f /dev/null
    env_file:
      - .env
